apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80 # if only port is defined than target port is the same
      # targetPort: 80
      nodePort: 30000
  selector:
    app: primeiro-pod
